#[derive(Clone)]
#[derive(Debug)]
#[allow(dead_code)]
pub enum Color {
    Black,
    Blue,
    Green,
    DarkTurquoise,
    Red,
    DarkPink,
    Brown,
    LightGrey,
    DarkGrey,
    LightBlue,
    BrightGreen,
    LightTurquoise,
    Salmon,
    Pink,
    Yellow,
    White,
    LightGreen,
    LightYellow,
    Tan,
    LightViolet,
    Purple,
    DarkBlueViolet,
    Orange,
    Magenta,
    Lime,
    DarkTan,
    BrightPink,
    MediumLavender,
    Lavender,
    VeryLightOrange,
    BrightReddishLilac,
    ReddishBrown,
    LightBluishGrey,
    DarkBluishGrey,
    MediumBlue,
    MediumGreen,
    LightPink,
    LightNougat,
    MediumNougat,
    MediumLilac,
    LightBrown,
    BlueViolet,
    Nougat,
    LightSalmon,
    Violet,
    MediumViolet,
    MediumLime,
    Aqua,
    LightLime,
    LightOrange,
    DarkSalmon,
    SpudOrange,
    DarkNougat,
    VeryLightBluishGrey,
    DarkYellow,
    BrightLightOrange,
    BrightLightBlue,
    MediumBlueViolet,
    Rust,
    ReddishLilac,
    Lilac,
    LightLilac,
    WarmYellowishOrange,
    BrightLightYellow,
    SkyBlue,
    DarkBlue,
    DarkGreen,
    FlamingoPink,
    DarkBrown,
    MaerskBlue,
    DarkRed,
    DarkAzure,
    MediumAzure,
    LightAqua,
    YellowishGreen,
    OliveGreen,
    SandRed,
    MediumDarkPink,
    Coral,
    EarthOrange,
    NeonYellow,
    MediumBrown,
    MediumTan,
    SandPurple,
    SandGreen,
    SandBlue,
    ReddishOrange,
}

pub struct ColorInfo {
    pub code: u32,
    pub value: &'static str,
    #[allow(dead_code)]
    pub name: &'static str,
}

impl Color {
    pub fn info(&self) -> ColorInfo {
        match self {
            Color::Black =>              ColorInfo { code: 0,   value: "#1B2A34", name: "Black" },
            Color::Blue =>               ColorInfo { code: 1,   value: "#1E5AA8", name: "Blue" },
            Color::Green =>              ColorInfo { code: 2,   value: "#00852B", name: "Green" },
            Color::DarkTurquoise =>      ColorInfo { code: 3,   value: "#069D9F", name: "Dark_Turquoise" },
            Color::Red =>                ColorInfo { code: 4,   value: "#B40000", name: "Red" },
            Color::DarkPink =>           ColorInfo { code: 5,   value: "#D3359D", name: "Dark_Pink" },
            Color::Brown =>              ColorInfo { code: 6,   value: "#543324", name: "Brown" },
            Color::LightGrey =>          ColorInfo { code: 7,   value: "#8A928D", name: "Light_Grey" },
            Color::DarkGrey =>           ColorInfo { code: 8,   value: "#545955", name: "Dark_Grey" },
            Color::LightBlue =>          ColorInfo { code: 9,   value: "#97CBD9", name: "Light_Blue" },
            Color::BrightGreen =>        ColorInfo { code: 10,  value: "#58AB41", name: "Bright_Green" },
            Color::LightTurquoise =>     ColorInfo { code: 11,  value: "#00AAA4", name: "Light_Turquoise" },
            Color::Salmon =>             ColorInfo { code: 12,  value: "#F06D61", name: "Salmon" },
            Color::Pink =>               ColorInfo { code: 13,  value: "#F6A9BB", name: "Pink" },
            Color::Yellow =>             ColorInfo { code: 14,  value: "#FAC80A", name: "Yellow" },
            Color::White =>              ColorInfo { code: 15,  value: "#F4F4F4", name: "White" },
            Color::LightGreen =>         ColorInfo { code: 17,  value: "#ADD9A8", name: "Light_Green" },
            Color::LightYellow =>        ColorInfo { code: 18,  value: "#FFD67F", name: "Light_Yellow" },
            Color::Tan =>                ColorInfo { code: 19,  value: "#D7BA8C", name: "Tan" },
            Color::LightViolet =>        ColorInfo { code: 20,  value: "#AFBED6", name: "Light_Violet" },
            Color::Purple =>             ColorInfo { code: 22,  value: "#671F81", name: "Purple" },
            Color::DarkBlueViolet =>     ColorInfo { code: 23,  value: "#0E3E9A", name: "Dark_Blue_Violet" },
            Color::Orange =>             ColorInfo { code: 25,  value: "#D67923", name: "Orange" },
            Color::Magenta =>            ColorInfo { code: 26,  value: "#901F76", name: "Magenta" },
            Color::Lime =>               ColorInfo { code: 27,  value: "#A5CA18", name: "Lime" },
            Color::DarkTan =>            ColorInfo { code: 28,  value: "#897D62", name: "Dark_Tan" },
            Color::BrightPink =>         ColorInfo { code: 29,  value: "#FF9ECD", name: "Bright_Pink" },
            Color::MediumLavender =>     ColorInfo { code: 30,  value: "#A06EB9", name: "Medium_Lavender" },
            Color::Lavender =>           ColorInfo { code: 31,  value: "#CDA4DE", name: "Lavender" },
            Color::VeryLightOrange =>    ColorInfo { code: 68,  value: "#FDC383", name: "Very_Light_Orange" },
            Color::BrightReddishLilac => ColorInfo { code: 69,  value: "#8A12A8", name: "Bright_Reddish_Lilac" },
            Color::ReddishBrown =>       ColorInfo { code: 70,  value: "#5F3109", name: "Reddish_Brown" },
            Color::LightBluishGrey =>    ColorInfo { code: 71,  value: "#969696", name: "Light_Bluish_Grey" },
            Color::DarkBluishGrey =>     ColorInfo { code: 72,  value: "#646464", name: "Dark_Bluish_Grey" },
            Color::MediumBlue =>         ColorInfo { code: 73,  value: "#7396C8", name: "Medium_Blue" },
            Color::MediumGreen =>        ColorInfo { code: 74,  value: "#7FC475", name: "Medium_Green" },
            Color::LightPink =>          ColorInfo { code: 77,  value: "#FECCCF", name: "Light_Pink" },
            Color::LightNougat =>        ColorInfo { code: 78,  value: "#FFC995", name: "Light_Nougat" },
            Color::MediumNougat =>       ColorInfo { code: 84,  value: "#AA7D55", name: "Medium_Nougat" },
            Color::MediumLilac =>        ColorInfo { code: 85,  value: "#441A91", name: "Medium_Lilac" },
            Color::LightBrown =>         ColorInfo { code: 86,  value: "#7B5D41", name: "Light_Brown" },
            Color::BlueViolet =>         ColorInfo { code: 89,  value: "#1C58A7", name: "Blue_Violet" },
            Color::Nougat =>             ColorInfo { code: 92,  value: "#BB805A", name: "Nougat" },
            Color::LightSalmon =>        ColorInfo { code: 100, value: "#F9B7A5", name: "Light_Salmon" },
            Color::Violet =>             ColorInfo { code: 110, value: "#26469A", name: "Violet" },
            Color::MediumViolet =>       ColorInfo { code: 112, value: "#4861AC", name: "Medium_Violet" },
            Color::MediumLime =>         ColorInfo { code: 115, value: "#B7D425", name: "Medium_Lime" },
            Color::Aqua =>               ColorInfo { code: 118, value: "#9CD6CC", name: "Aqua" },
            Color::LightLime =>          ColorInfo { code: 120, value: "#DEEA92", name: "Light_Lime" },
            Color::LightOrange =>        ColorInfo { code: 121, value: "#F89A39", name: "Light_Orange" },
            Color::DarkSalmon =>         ColorInfo { code: 123, value: "#EE5434", name: "Dark_Salmon" },
            Color::SpudOrange =>         ColorInfo { code: 125, value: "#F9A777", name: "Spud_Orange" },
            Color::DarkNougat =>         ColorInfo { code: 128, value: "#AD6140", name: "Dark_Nougat" },
            Color::VeryLightBluishGrey =>ColorInfo { code: 151, value: "#C8C8C8", name: "Very_Light_Bluish_Grey" },
            Color::DarkYellow =>         ColorInfo { code: 180, value: "#DD982E", name: "Dark_Yellow" },
            Color::BrightLightOrange =>  ColorInfo { code: 191, value: "#FCAC00", name: "Bright_Light_Orange" },
            Color::BrightLightBlue =>    ColorInfo { code: 212, value: "#9DC3F7", name: "Bright_Light_Blue" },
            Color::MediumBlueViolet =>   ColorInfo { code: 213, value: "#476FB6", name: "Medium_Blue_Violet" },
            Color::Rust =>               ColorInfo { code: 216, value: "#872B17", name: "Rust" },
            Color::ReddishLilac =>       ColorInfo { code: 218, value: "#8E5597", name: "Reddish_Lilac" },
            Color::Lilac =>              ColorInfo { code: 219, value: "#564E9D", name: "Lilac" },
            Color::LightLilac =>         ColorInfo { code: 220, value: "#9195CA", name: "Light_Lilac" },
            Color::WarmYellowishOrange =>ColorInfo { code: 225, value: "#FAA964", name: "Warm_Yellowish_Orange" },
            Color::BrightLightYellow =>  ColorInfo { code: 226, value: "#FFEC6C", name: "Bright_Light_Yellow" },
            Color::SkyBlue =>            ColorInfo { code: 232, value: "#77C9D8", name: "Sky_Blue" },
            Color::DarkBlue =>           ColorInfo { code: 272, value: "#19325A", name: "Dark_Blue" },
            Color::DarkGreen =>          ColorInfo { code: 288, value: "#00451A", name: "Dark_Green" },
            Color::FlamingoPink =>       ColorInfo { code: 295, value: "#FF94C2", name: "Flamingo_Pink" },
            Color::DarkBrown =>          ColorInfo { code: 308, value: "#352100", name: "Dark_Brown" },
            Color::MaerskBlue =>         ColorInfo { code: 313, value: "#ABD9FF", name: "Maersk_Blue" },
            Color::DarkRed =>            ColorInfo { code: 320, value: "#720012", name: "Dark_Red" },
            Color::DarkAzure =>          ColorInfo { code: 321, value: "#469BC3", name: "Dark_Azure" },
            Color::MediumAzure =>        ColorInfo { code: 322, value: "#68C3E2", name: "Medium_Azure" },
            Color::LightAqua =>          ColorInfo { code: 323, value: "#D3F2EA", name: "Light_Aqua" },
            Color::YellowishGreen =>     ColorInfo { code: 326, value: "#E2F99A", name: "Yellowish_Green" },
            Color::OliveGreen =>         ColorInfo { code: 330, value: "#77774E", name: "Olive_Green" },
            Color::SandRed =>            ColorInfo { code: 335, value: "#88605E", name: "Sand_Red" },
            Color::MediumDarkPink =>     ColorInfo { code: 351, value: "#F785B1", name: "Medium_Dark_Pink" },
            Color::Coral =>              ColorInfo { code: 353, value: "#FF6D77", name: "Coral" },
            Color::EarthOrange =>        ColorInfo { code: 366, value: "#D86D2C", name: "Earth_Orange" },
            Color::NeonYellow =>         ColorInfo { code: 368, value: "#EDFF21", name: "Neon_Yellow" },
            Color::MediumBrown =>        ColorInfo { code: 370, value: "#755945", name: "Medium_Brown" },
            Color::MediumTan =>          ColorInfo { code: 371, value: "#CCA373", name: "Medium_Tan" },
            Color::SandPurple =>         ColorInfo { code: 373, value: "#75657D", name: "Sand_Purple" },
            Color::SandGreen =>          ColorInfo { code: 378, value: "#708E7C", name: "Sand_Green" },
            Color::SandBlue =>           ColorInfo { code: 379, value: "#70819A", name: "Sand_Blue" },
            Color::ReddishOrange =>      ColorInfo { code: 402, value: "#CA4C0B", name: "Reddish_Orange" },
        }
    }

    pub fn all() -> Vec<Color> {
        vec![
            Color::Black,
            Color::Blue,
            Color::Green,
            Color::DarkTurquoise,
            Color::Red,
            Color::DarkPink,
            Color::Brown,
            Color::LightGrey,
            Color::DarkGrey,
            Color::LightBlue,
            Color::BrightGreen,
            Color::LightTurquoise,
            Color::Salmon,
            Color::Pink,
            Color::Yellow,
            Color::White,
            Color::LightGreen,
            Color::LightYellow,
            Color::Tan,
            Color::LightViolet,
            Color::Purple,
            Color::DarkBlueViolet,
            Color::Orange,
            Color::Magenta,
            Color::Lime,
            Color::DarkTan,
            Color::BrightPink,
            Color::MediumLavender,
            Color::Lavender,
            Color::VeryLightOrange,
            Color::BrightReddishLilac,
            Color::ReddishBrown,
            Color::LightBluishGrey,
            Color::DarkBluishGrey,
            Color::MediumBlue,
            Color::MediumGreen,
            Color::LightPink,
            Color::LightNougat,
            Color::MediumNougat,
            Color::MediumLilac,
            Color::LightBrown,
            Color::BlueViolet,
            Color::Nougat,
            Color::LightSalmon,
            Color::Violet,
            Color::MediumViolet,
            Color::MediumLime,
            Color::Aqua,
            Color::LightLime,
            Color::LightOrange,
            Color::DarkSalmon,
            Color::SpudOrange,
            Color::DarkNougat,
            Color::VeryLightBluishGrey,
            Color::DarkYellow,
            Color::BrightLightOrange,
            Color::BrightLightBlue,
            Color::MediumBlueViolet,
            Color::Rust,
            Color::ReddishLilac,
            Color::Lilac,
            Color::LightLilac,
            Color::WarmYellowishOrange,
            Color::BrightLightYellow,
            Color::SkyBlue,
            Color::DarkBlue,
            Color::DarkGreen,
            Color::FlamingoPink,
            Color::DarkBrown,
            Color::MaerskBlue,
            Color::DarkRed,
            Color::DarkAzure,
            Color::MediumAzure,
            Color::LightAqua,
            Color::YellowishGreen,
            Color::OliveGreen,
            Color::SandRed,
            Color::MediumDarkPink,
            Color::Coral,
            Color::EarthOrange,
            Color::NeonYellow,
            Color::MediumBrown,
            Color::MediumTan,
            Color::SandPurple,
            Color::SandGreen,
            Color::SandBlue,
            Color::ReddishOrange,
        ]
    }
}
